### PR TITLE
added views and templates

### PR DESCRIPTION
**Pull request by tyler-simeone**
- Added base file structure with views and templates.
- Didn't add url patterns for the views yet.

- git fetch --all
- git checkout -b ts-createFileStructure

- Should see updated file structure. 🙂

### CODE REVIEW

**Review by mister-michael — COMMENTED** [review]
looks good! rocket ship eggplant tear champagne

**Comment by mister-michael** [comment]
thumbs up!

**Comment by matthewbaker22** [comment]
Looks good

**Review by CoopNich — APPROVED** [review]

**Review by mister-michael — APPROVED** [review]
approved!

**Pull request merged**
